### PR TITLE
Make it work with expo

### PR DESCRIPTION
**Pull request by gustavoggs**
Based on this: https://github.com/expo/expo/issues/15622#issuecomment-997141629

### CODE REVIEW

**Comment by lufinkey** [comment]
Won't this break it in non-expo builds?

**Comment by gustavoggs** [comment]
@lufinkey I don't think, but I don't have any project without expo to test it.

**Comment by lufinkey** [comment]
Do you have an example of this change being done in other repos to add expo
support?

**Comment by gustavoggs** [comment]
It was suggested by expo:

https://github.com/expo/expo/issues/15622#issuecomment-997141629

**Comment by gustavoggs** [comment]
Expo are moving back in their change as it caused problem in multiple libraries, but good to check if it is not good to continue with this PR.

https://github.com/expo/expo/issues/15622#issuecomment-999609806

**Comment by lufinkey** [comment]
gotcha, so I should close this?

**Comment by Kudo** [comment]
hi there! i would still recommend to land this change for modern react-native support. the double-quoted import is for react-native < 0.40 which is really outdated for a while. modern react-native uses CocoaPods to manage dependency, the `#import <>` style is recommended.

there're still some other code recommended to update:

1.
https://github.com/lufinkey/react-native-events/blob/d34c2139b8d4f2920ecbc91af8203bc0aaf59aa4/ios/RNEventEmitter.h#L2-L6

2. update README.md also for other modules to import header

```diff
--- README.md   2022-01-09 21:14:58.000000000 +0800
+++ README.md.new       2022-01-09 22:43:16.000000000 +0800
@@ -29,17 +29,9 @@
 ```objc
 // MyNativeModule.h

-#if __has_include("RCTBridgeModule.h")
-#import "RCTBridgeModule.h"
-#else
 #import <React/RCTBridgeModule.h>
-#endif

-#if __has_include("RNEventEmitter.h")
-#import "RNEventEmitter.h"
-#else
 #import <RNEventEmitter/RNEventEmitter.h>
-#endif

 @interface MyNativeModule : NSObject <RCTBridgeModule, RNEventConformer>

```

3. thought this one is not related to expo directly. i'd recommend to depend on `React-Core` for [better CocoaPods `use_frameworks!` support](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)

```diff
--- RNEventEmitter.podspec      2022-01-09 21:14:58.000000000 +0800
+++ RNEventEmitter.podspec.new  2022-01-09 22:47:14.000000000 +0800
@@ -15,5 +15,5 @@
   s.source       = { :git => package['repository']['url'], :tag => "v#{s.version}" }
   s.source_files  = "ios/**/*.{h,m}"

-  s.dependency 'React'
+  s.dependency 'React-Core'
 end
```

**Comment by lufinkey** [comment]
@Kudo if you can give examples of other large react native projects making this change without breaking other projects than I'll merge it

**Comment by Kudo** [comment]
@lufinkey take `react-native-safe-area-context` as an example, they will have `#import <React/*.h>` import.

https://github.com/th3rdwave/react-native-safe-area-context/blob/fa3957766143086c8f115f394b700875e20ee422/ios/SafeAreaView/RNCSafeAreaProviderManager.h#L1

another one is `react-native-reanimated`:

https://github.com/software-mansion/react-native-reanimated/blob/9fcfcbb367b623eeb8a73931d52cbad69c619212/ios/REAModule.h#L1-L6

please let me know if you still want other examples. thank you!

**Comment by lufinkey** [comment]
Neither of those seem to be importing RCTBridge.h

**Comment by lufinkey** [comment]
It also seems if we'd want to make this update it needs to be in more places than just this header `RCTEventEmitter.h` also uses the same include check

**Comment by lufinkey** [comment]
I took a look at a few other modules and this does seem to be safe. I'd just say update in the other spots and it should be fine to merge

**Comment by gustavoggs** [comment]
I will take a look tomorrow what other parts needs to be update and will update this PR

**Comment by Kudo** [comment]
awesome!  thanks for all your help.

**Comment by gustavoggs** [comment]
@lufinkey did the updates suggested by @Kudo

**Comment by lufinkey** [comment]
@gustavoggs I could be wrong but I think `React` still needs to be a dependency. Those other modules @Kudo linked to still had in their podspec

**Comment by gustavoggs** [comment]
I will revert this last commit and we can do in a separate PR

**Comment by Kudo** [comment]
@lufinkey that's nice to have which breaks `use_frameworks!`. reanimated has `React` because it hacks a lot into react-native core, i think that's an exception 😅

you can verify the error by the steps:

```sh
$ npx react-native init RN066 --version 0.66
$ cd RN066
$ yarn add react-native-events
# edit ios/Podfile to add use_frameworks!
$ cd ios && rm -rf Pods && pod install && cd ..
$ yarn ios
```

**Comment by lufinkey** [comment]
@Kudo Can you clarify this comment? I'm not sure I understand what you mean by it

**Comment by Kudo** [comment]
@lufinkey uh i mean to add `use_frameworks!` to ios/Podfile like this.

```diff
--- a/ios/Podfile
+++ b/ios/Podfile
@@ -12,6 +12,8 @@ target 'RN066' do
     :hermes_enabled => false
   )

+  use_frameworks!
+
   target 'RN066Tests' do
     inherit! :complete
     # Pods for testing
```

if you depend on `React` but not `React-Core`, in the `use_frameworks!` case, compile will fail.
as far as i know, some mobile SDKs suggest developers to add this option to build libraries as iOS frameworks, e.g. [Firebase](https://firebase.google.com/docs/ios/link-firebase-static-dynamic). the problem is not related to Expo SDK. i'm just seeing the problem and share with you.

**Comment by gustavoggs** [comment]
I created a separated PR for the change of the dependency to make it easier to review this and release: https://github.com/lufinkey/react-native-events/pull/10

**Comment by lufinkey** [comment]
Thanks! I appreciate it

**Pull request merged**
